# NumPyをimportする

In [1]:
import numpy as np

<br>

# ベクトルの表現
NumPyのarray(配列)を使って、以下の数ベクトルを表現する
$$
\boldsymbol{x} = \begin{pmatrix}1 \\ 2 \\ 3 \end{pmatrix}
$$

In [2]:
x = np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

### ベクトルの型
また、上で定義したベクトルの型を.shapeで確認できる

`(3,)の場合、3行1列の行列(つまりベクトル)`

In [4]:
x.shape

(3,)

### ベクトルの次元
$$
dim \begin{pmatrix}1 \\ 2 \\ 3 \end{pmatrix} = 1
$$
は、以下のように求めることができる

In [5]:
x.ndim

1

<br>

# 行列の表現
NumPyで以下のような3x3型の行列を表現する
$$
A = \begin{pmatrix}
   1 & 2 \\
   3 & 4 \\
   5 & 6
\end{pmatrix}
$$

In [6]:
A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [7]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

### 行列の型と次元
ベクトルの時と同様に、行列の型と次元は以下のように求められる

In [8]:
A.shape

(3, 2)

In [9]:
A.ndim

2

### 行列の転置


In [10]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

### 行列の積
以下のような行列の積を求める際は、`dot()`メソッドを用いる
$$
A(^tA) = 
\begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix}
\begin{pmatrix} 1 & 3 & 5\\ 2 & 4 & 6 \end{pmatrix}
$$

In [11]:
np.dot(A, A.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

### 零行列
np.zerosを使うと、引数に指定した型の零行列を作ることができる

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<br>

# 行列に対する基本統計量

### 行列の平均値
以下のような行列yに関して、`mean()`メソッドを用いると全ての要素に対する平均値を求められる

In [13]:
y = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [14]:
y.mean()

5.0

### 各行の平均値
先ほどの`mean()`メソッドに対して、引数に`axis=1`を指定するとこで、各行に関する平均値を求めることができる

In [15]:
y.mean(axis=1)

array([2., 5., 8.])

### 行列の分散
`var()`メソッドを用いることで、行列の分散を求めることができる

In [16]:
y.var()

6.666666666666667

### 行列の標準偏差
`std()`メソッドを用いることで、行列の分散を求めることができる

In [17]:
y.std()

2.581988897471611

### 行列の要素の最大値
`max()`メソッドを用いることで、行列の全ての要素の中で最大値を求めることができる<br>
また、引数に`axis=1`を与えることで、各行の要素の中の最大値が出力される

In [18]:
y.max()

9

In [19]:
y.max(axis=1)

array([3, 6, 9])

<br>

参考: https://www.youtube.com/watch?v=qMjK2131f3I